#!/usr/bin/env python3
"""Create a new Engineering Report Stack project skeleton."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

DATA_DIRS = ("sources", "requirements", "tests", "results", "evidence")
EVIDENCE_DIRS = ("images", "logs", "measurements", "documents")
TEMPLATE_NAMES = ("compliance", "validation", "test", "handoff")

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_ROOT = ROOT / "templates"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create a new engineering report project")
    parser.add_argument("destination", help="directory to create")
    parser.add_argument("--id", required=True, dest="report_id", help="stable report ID, e.g. RPT-MAIN-V3")
    parser.add_argument("--name", required=True, help="human-readable report name")
    parser.add_argument("--version", default="0.1.0", help="initial report version")
    parser.add_argument("--description", default="", help="optional report description")
    parser.add_argument(
        "--template",
        choices=TEMPLATE_NAMES,
        default="validation",
        help="report profile to scaffold",
    )
    parser.add_argument(
        "--format",
        choices=("json", "yaml"),
        default="yaml",
        help="canonical authoring format for report metadata",
    )
    return parser


def load_profile(name: str) -> dict:
    path = TEMPLATE_ROOT / name / "profile.json"
    return json.loads(path.read_text(encoding="utf-8"))


def write_report_metadata(root: Path, report: dict, fmt: str) -> Path:
    if fmt == "json":
        path = root / "report.json"
        path.write_text(
            json.dumps(report, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        return path

    path = root / "report.yaml"
    path.write_text(
        yaml.safe_dump(
            report,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
        ),
        encoding="utf-8",
    )
    return path


def render_plan(profile: dict) -> str:
    lines = [
        "# Report Plan",
        "",
        f"**Template:** {profile['title']}",
        "",
        profile["description"],
        "",
        "## Recommended section tree",
        "",
    ]
    for section in profile["sections"]:
        lines.append(f"- {section}")

    lines.extend(["", "## Emphasis", ""])
    for item in profile["emphasis"]:
        lines.append(f"- {item}")

    lines.extend([
        "",
        "## Canonical data flow",
        "",
        "```text",
        "Source -> Requirement -> Test -> Result -> Evidence",
        "```",
        "",
        "Adapt this plan to the project; do not duplicate canonical facts into this file.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    args = build_parser().parse_args()

    if not args.report_id.startswith("RPT-"):
        print("ERROR report id must start with RPT-", file=sys.stderr)
        return 2

    root = Path(args.destination).expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        print(f"ERROR destination is not empty: {root}", file=sys.stderr)
        return 3

    root.mkdir(parents=True, exist_ok=True)
    for name in DATA_DIRS:
        directory = root / "data" / name
        directory.mkdir(parents=True, exist_ok=True)
        (directory / ".gitkeep").touch()
    for name in EVIDENCE_DIRS:
        directory = root / "evidence" / name
        directory.mkdir(parents=True, exist_ok=True)
        (directory / ".gitkeep").touch()

    profile = load_profile(args.template)
    report = {
        "id": args.report_id,
        "name": args.name,
        "version": args.version,
        "description": args.description or profile["description"],
        "status": "draft",
        "renderers": ["vitepress"],
        "metadata": {
            "template": profile["id"],
            "template_title": profile["title"],
        },
    }
    metadata_path = write_report_metadata(root, report, args.format)
    (root / "REPORT_PLAN.md").write_text(render_plan(profile), encoding="utf-8")

    readme = f"""# {args.name}

Canonical engineering report project generated by Engineering Report Stack.

## Template

{profile["title"]}

## Canonical data flow

Source -> Requirement -> Test -> Result -> Evidence

## Validate

From the Engineering-Report-Stack repository:

    npm run report:check

For an external project path:

    engineering-report validate {root}

Do not edit generated report output as the source of truth. Edit canonical files under data/ and regenerate.
"""
    (root / "README.md").write_text(readme, encoding="utf-8")

    print(f"OK    created report project: {root}")
    print(f"ID    {args.report_id}")
    print(f"TYPE  {profile['id']}")
    print(f"DATA  {metadata_path.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
