#!/usr/bin/env python3
"""Create a new Engineering Report Stack project skeleton."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DATA_DIRS = ("sources", "requirements", "tests", "results", "evidence")
EVIDENCE_DIRS = ("images", "logs", "measurements", "documents")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create a new engineering report project")
    parser.add_argument("destination", help="directory to create")
    parser.add_argument("--id", required=True, dest="report_id", help="stable report ID, e.g. RPT-MAIN-V3")
    parser.add_argument("--name", required=True, help="human-readable report name")
    parser.add_argument("--version", default="0.1.0", help="initial report version")
    parser.add_argument("--description", default="", help="optional report description")
    return parser


def main() -> int:
    args = build_parser().parse_args()

    if not args.report_id.startswith("RPT-"):
        print("ERROR report id must start with RPT-", file=sys.stderr)
        return 2

    root = Path(args.destination).expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        print(f"ERROR destination is not empty: {root}", file=sys.stderr)
        return 3

    root.mkdir(parents=True, exist_ok=True)
    for name in DATA_DIRS:
        (root / "data" / name).mkdir(parents=True, exist_ok=True)
    for name in EVIDENCE_DIRS:
        (root / "evidence" / name).mkdir(parents=True, exist_ok=True)

    report = {
        "id": args.report_id,
        "name": args.name,
        "version": args.version,
        "description": args.description,
        "status": "draft",
        "renderers": ["vitepress"],
    }
    (root / "report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    readme = f"""# {args.name}

Canonical engineering report project generated by Engineering Report Stack.

## Data flow

Source -> Requirement -> Test -> Result -> Evidence

## Validate

From the Engineering-Report-Stack repository:

    python3 tools/report_cli.py validate {root}

Do not edit generated report output as the source of truth. Edit canonical files under data/ and regenerate.
"""
    (root / "README.md").write_text(readme, encoding="utf-8")

    print(f"OK    created report project: {root}")
    print(f"ID    {args.report_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
